version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    ports:
      - '27017:27017'
    volumes:
      - 'mongodata:/data/db'

  proxy:
    build: 
      context: ./proxy
      dockerfile: Dockerfile.dev
    container_name: proxy
    restart: on-failure
    depends_on:
      - 'api'
      - 'client'
    ports:
      - '80:80'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api
    depends_on:
      - 'mongo'
    ports:
      - '5000:5000'
    env_file:
      - './api/.env'
    volumes:
      - './api/node_modules:/usr/src/app/node_modules'
      - './api:/usr/src/app'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - './client/node_modules:/usr/src/app/node_modules'
      - './client/src:/usr/src/app/src'
    environment:
      - WDS_SOCKET_PORT=0

volumes:
  mongodata:
